### ISSUE TITLE
关于设置cookie的一个建议

### ISSUE THREAD

**Issue by AceLing** [cupools/cupools.github.io#1]
几个好用的函数
function setCookie(c_name, value, expiredays) {
    var exdate = new Date();
    exdate.setDate(exdate.getDate() + expiredays);
    document.cookie = c_name + '=' + window.escape(value) + ((!expiredays) ? '' : ';expires=' + exdate.toGMTString());
}

setDate是设置当前月的某一日，建议使用setTime

**Comment by AceLing** [comment]
更正：可以用getDate()
若是傳入的值超出當月份的正常範圍，setDate()方法也會依據超出的數值進行計算，譬如setDate(0)會讓日期變成前一個月的最後一天，setDate(-1)會讓日期變成前一個月的倒數第二天。若當月有31天，那setDate(32)會讓日期變成下個月的第一天。Orz。。

**Comment by AceLing** [comment]
使用toGMTString(), toUTCString()的兼容性问题
设置expires的时候
chrome：expires = 代码设置的时间 +- 时差
firefox：expires = 代码设置的时间

关于时差：由于国内是东八区，所以与UTC标准相差+8小时

**Comment by cupools** [comment]
这个不会影响到 `cookie` 过期时间的样子

**Comment by AceLing** [comment]
不会影响是指？但是查看出来的是不一样的喔

**Comment by cupools** [comment]
`cookie` 的过期时间格式需要是 `UTC` 或 `GMT`，两者不受时区影响。详细见 [这里](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/cookie) 和  [这里](http://techpatterns.com/forums/about849.html)

然后 Chrome 和 Firefox 的兼容我试了下没发现有什么问题啊，都没有时差

**Comment by AceLing** [comment]
chrome显示出来的时间是比我设置的时间少8个小时的，而firefox显示出来的时间就是我设置的时间

**Comment by cupools** [comment]
噗我这边 windows 和 OS X 试了 Chrome 和 Firefox 都没有出现你说的问题啊

**Comment by cupools** [comment]
话说你说的是这样的问题吧

``` javascript
var d = new Date();

console.log(d);
// ==> Chrome: Mon Nov 30 2015 11:14:03 GMT+0800 (中国标准时间)
// ==> Firefox: Date 2015-11-30T03:12:49.913Z

console.log(d.toGMTString());
// ==> Chrome: "Mon, 30 Nov 2015 03:14:03 GMT"
// ==> Firefox: "Mon, 30 Nov 2015 03:12:49 GMT"
```

这个没有影响啊....

**Comment by AceLing** [comment]
明白了~！

**Comment by cupools** [comment]
撒花~
